# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_info', '0002_auto_20170402_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='released',
            field=models.BooleanField(default=False, help_text='(Allow patient to view these test results)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
