# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='fromdel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='todel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='message',
            field=models.TextField(max_length=50),
        ),
    ]
