# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
