# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-26 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170416_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_email',
            field=models.IntegerField(blank=True, help_text='Format: 99999999999', null=True, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in Inches', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
